name: Bug Report
description: Submit bug report.
title: 'Bug: '
labels: ['bug']
assignees:
  - ya7on
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result 
      description: What actually happened?
      placeholder: Does not work
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected result 
      description: What did you expect to happen?
      placeholder: Work
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: What device, OS and browser are you using?
      placeholder: Desktop, Ubuntu, Mozila
