name: Bug Report
description: Submit bug report.
title: 'Bug: '
labels: ['bug']
assignees:
  - ya7on
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: 1. Go to '...'
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you using?
      options:
        - Desktop
        - Mobile device
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
