name: Code checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  merge_group:
    types: [ checks_requested ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: NPM Install
      run: npm install

    - name: NPM Build
      run: npm run build

    - name: Linter
      run: npm run lint
